# Generated by Django 4.1.4 on 2023-01-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem", old_name="variation", new_name="variations",
        ),
    ]
